### PR TITLE
Fix:Correpondence and its icon out off there box in chesslaBlab website #432

### LINKED ISSUE #432: Correpondence and its icon out off there box in chesslaBlab website
hello,

I found an issue in your chesslaBlab website . a correspondence and its icon is outoff from there box  for the small screen devices . please check it
And I want to work on this issue ...please assign me of this issue
2023-06-20-09_51_01-screenshot

### PR DESCRIPTION
**Pull request by techmannih**
Issue #432 

Closes #432

DISCRIPTION

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

TYPE OF CHANGE

replace in media query  (min-width:900px)  to    (min-width:1100px)

### CODE REVIEW

**Comment by programarivm** [comment]
Thank you @techmannih for sending this PR, we're on the right track.

Let me suggest to not change the media queries. Instead, let's rename the **Correspondence** button as **Inbox** in the [src/features/nav/Nav.js](https://github.com/chesslablab/react-chess/blob/master/src/features/nav/Nav.js) component. 

Keep it up, and happy learning and coding!

File: src/features/nav/Nav.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ const Nav = ({props}) => {
   const [anchorElOpeningSearch, setAnchorElOpeningSearch] = useState(null);
   const [anchorElCorrespondence, setAnchorElCorrespondence] = useState(null);
 
-  const matches = useMediaQuery("(min-width:900px)");
+  const matches = useMediaQuery("(min-width:1100px)");
```
Comment (programarivm) [inline src/features/nav/Nav.js:57]: Let me suggest to not change this, instead, let's rename Correspondence as Inbox.

**Comment by techmannih** [comment]
Thankyou ! @programarivm
